### ISSUE TITLE
Can't compile from master branch

### ISSUE THREAD

**Issue by arpunk** [fare/gerbil-crypto#1]
Hello @fare,

Been trying to get `glow` up and running but I get the following error while trying to compile `gerbil-crypto`:

```sh
$ gxpkg install github.com/fare/gerbil-crypto
... install github.com/fare/gerbil-crypto
... build github.com/fare/gerbil-crypto
... compile keccak
Gerbil v0.16-178-g17fbcb95 on Gambit v4.9.3-1389-g55b21ed9
*** ERROR IN std/misc/concurrent-plan#perform-plan/threads__% -- Failure to build (gxc: "keccak" "-cc-options" "-I/home/arpunk/.gerbil/pkg/github.com/fare/gerbil-crypto" "-ld-options" #f "-cc-options" #f) "(Argument 1) STRING or port settings expected\n(o
pen-process\n '(path: \"/usr/local/Gambit/bin/gsc\" arguments: (\"-:i8,f8,-8,t8\" \"-cc-o... #106\n)\n"
Process exited with non-zero status
512
(path: "/home/arpunk/.gerbil/pkg/github.com/fare/gerbil-crypto/build.ss" arguments: ("compile") environment: #f directory: "~/.gerbil/pkg/github.com/fare/gerbil-crypto" stdin-redirection: #t stdout-redirection: #f stderr-redirection: #f pseudo-termina...
$
```

I don't think I need any extra dependencies, my OpenSSL version is 1.1.1k if that's relevant. Do you have any workarounds I can try?

**Comment by fare** [comment]
Just to be clear—are you building using Gerbil as installed with Nix, or did you build your own Gambit and/or Gerbil? Is `nix-shell` in your `$PATH` ? The build system (more precisely, `clan/building` from `gerbil-utils`) assumes that if `nix-shell` is present then the library dependencies (i.e. openssl) shall be retrieved from Nix; otherwise it uses `pkg-config` at which point you need it installed and configured.

What does `pkg-config --libs openssl` and `pkg-config --cflags openssl` return? What do they print, what is the error status code if any?

Still, at the very least, this is a confusing error message, that should be improved upon.

**Comment by arpunk** [comment]
I did build my own Gambit/Gerbil, both from latest `master`. I don't use `nix`, just plain Fedora.

```
$ pkg-config --libs openssl
-lssl -lcrypto
$ pkg-config --cflags openssl

$
```

The last command doesn't produce any output. FWIW the dependency used to compile just fine.

Edit: I'm going to try in another env I have available later this afternoon and will let you know how it goes.

**Comment by fare** [comment]
It looks like to me that there might be a bug in the `pkg-config-options` function in [`clan/building`](https://github.com/fare/gerbil-utils/blob/master/building.ss). If you're a knowledgeable Gerbil user, maybe you can help us debug it. I'll try to give it a try soon, but I'm a bit overwhelmed this week.

**Comment by fare** [comment]
Aha, the issue is not openssl, but libsecp256k1. What do these return for you?

```
pkg-config --libs libsecp256k1
pkg-config --cflags libsecp256k1
```

I think the code might be working, but "just" failing to output a usable error message. I just pushed an update to `gerbil-utils` to improve the error message somewhat.

**Comment by arpunk** [comment]
You were right, the problem was the missing libsecp256k1 headers. It's now working properly, sorry for the noise.

**Comment by fare** [comment]
Not noise at all: the build system was failing to output a useful error message, and the README was failing to document the dependency. Thanks a lot for the report!
